language: node_js
node_js:
  - "6"
before_install:
  - cd ../../ && git clone https://github.com/MichMich/MagicMirror
  - mv SteffMUC/MMM-RadioDe MagicMirror/modules
  - cd MagicMirror && npm install express
  - cd modules/MMM-RadioDe
before_script:
  - npm install grunt-cli -g
